library(shiny)
library(ggvis)
library(SummarizedExperiment)
library(clusterExperiment)
#library(shinyjs)
library(stringr)
options(getClass.msg=FALSE) 
source("utilityFunctions.R")
source("startPage.R")
source("clusterManyPage.R")
source("plotClusterModule.R")
source("loadFiles.R")
source("combineMany.R")
source("makeDendrogram.R")
source("mergeClusters.r")
source("plotDendrogram.r")
source("plotHeatmap.r")
source("plotCoClustering.r")
source("saveObject.r")
sE <- SummarizedExperiment()
#Making a fake arbitrary clusterExperiment Object for convenience, want to find a better way!
cE <- clusterExperiment(matrix(data = c(0,0)), clusters = c(0), transformation = function(x){x})
