library(shiny)
library(ggvis)
library(SummarizedExperiment)
library(clusterExperiment)
library(shinyjs)
options(getClass.msg=FALSE) 

source("startPage.R")
source("clusterManyPage.R")
source("plotClusterModule.R")
source("loadFiles.R")
